/**
 * Centralized guest-facing UI copy to keep localization updates in one place.
 */

export const guestStrings = {
    facilityPanelTitle: "Cơ sở y tế gần bạn",
    searchPlaceholder: "Tìm theo tên cơ sở...",
    radiusLabel: "Bán kính tìm kiếm",
    loadingFacilities: "Đang tải danh sách cơ sở...",
    facilityLoadError: "Không thể tải dữ liệu cơ sở y tế. Vui lòng thử lại.",
    noFacilities: "Không tìm thấy cơ sở phù hợp trong phạm vi hiện tại.",
    locateButton: "Định vị",
    hospitalScreenButton: "Bệnh viện",
    facilityTypeAll: "Tất cả",
    facilityTypeHospital: "Hospital",
    facilityTypeClinic: "Clinic",
    facilityTypePharmacy: "Pharmacy",
    facilityTypeHospitalVi: "Bệnh viện",
    facilityTypeClinicVi: "Phòng khám",
    facilityTypePharmacyVi: "Nhà thuốc",
    detailTitle: "Chi tiết cơ sở",
    detailLabelType: "Loại",
    detailLabelAddress: "Địa chỉ",
    detailLabelHotline: "Hotline",
    detailLabelOpeningHours: "Giờ mở cửa",
    detailLabelDistance: "Khoảng cách",
    detailPhoneFallback: "Chưa có số hotline",
    detailOpeningHoursFallback: "Chưa cập nhật giờ mở cửa",
    detailDistanceFallback: "Chưa xác định khoảng cách",
    closeFacilityDetailAria: "Close facility detail",
    searchResultSuffix: "kết quả",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    directionsButton: "Get Directions",
    directionsNeedGps: "Vui lòng cấp quyền vị trí để mở chỉ đường.",
    locationRequesting: "Đang xác định vị trí GPS...",
    locationReady: "Đã cập nhật vị trí hiện tại.",
    locationDenied: "Vui lòng cho phép truy cập vị trí để sử dụng tính năng này.",
    locationFailed: "Không thể lấy vị trí. Vui lòng thử lại.",
    sosButton: "🚨 SOS Khẩn Cấp",
    sosPrepareError: "Không thể gửi SOS khi chưa có vị trí.",
    sosModalTitle: "Xác nhận gửi yêu cầu SOS",
    sosModalSubtitle: "Vị trí sẽ được gửi tới trung tâm điều phối cấp cứu.",
    sosPhoneLabel: "Số điện thoại nạn nhân",
    sosPhonePlaceholder: "Ví dụ: 0901234567",
    sosPhoneRequired: "Vui lòng nhập số điện thoại.",
    sosPhoneInvalid: "Số điện thoại không hợp lệ.",
    sosCancel: "Hủy",
    sosConfirm: "Confirm & Send SOS",
    sosSending: "Đang gửi yêu cầu SOS...",
    sosSendFailed: "Gửi SOS thất bại. Vui lòng thử lại.",
    sosSuccessTitle: "Yêu cầu SOS đã được gửi!",
    sosSuccessBody: "Xe cứu thương đang trên đường đến.",
    assignedHospitalLabel: "Bệnh viện phụ trách",
    assignedHospitalHotline: "Hotline",
    trackingFallback: "Xe cứu thương đang di chuyển tới vị trí của bạn.",
    trackingAssigned: "Xe cứu thương đã được điều phối.",
    trackingEtaPrefix: "Xe cứu thương cách bạn",
    trackingEtaSuffix: "phút",
    trackingReconnect: "Đang kết nối lại...",
    trackingModeBadge: "Chế độ theo dõi cấp cứu",
    rescueCompleted: "Xe cứu thương đã đến nơi.",
    locationStatusUnknown: "Chưa có vị trí hiện tại.",
    returnToMap: "Return to Map",
    retry: "Thử lại",
} as const;
