/**
 * Centralized guest-facing UI copy to keep localization updates in one place.
 */

export const guestStrings = {
    facilityPanelTitle: "Cơ sở y tế gần bạn",
    searchPlaceholder: "Tìm theo tên cơ sở...",
    radiusLabel: "Bán kính tìm kiếm",
    loadingFacilities: "Đang tải danh sách cơ sở...",
    facilityLoadError: "Không thể tải dữ liệu cơ sở y tế. Vui lòng thử lại.",
    noFacilities: "Không tìm thấy cơ sở phù hợp trong phạm vi hiện tại.",
    locateButton: "Định vị",
    hospitalScreenButton: "Bệnh viện",
    facilityTypeAll: "Tất cả",
    facilityTypeHospital: "Bệnh viện",
    facilityTypeClinic: "Phòng khám",
    facilityTypePharmacy: "Nhà thuốc",
    facilityTypeHospitalVi: "Bệnh viện",
    facilityTypeClinicVi: "Phòng khám",
    facilityTypePharmacyVi: "Nhà thuốc",
    detailTitle: "Chi tiết cơ sở",
    detailLabelType: "Loại",
    detailLabelAddress: "Địa chỉ",
    detailLabelHotline: "Hotline",
    detailLabelOpeningHours: "Giờ mở cửa",
    detailLabelDistance: "Khoảng cách",
    detailPhoneFallback: "Chưa có số hotline",
    detailOpeningHoursFallback: "Chưa cập nhật giờ mở cửa",
    detailDistanceFallback: "Chưa xác định khoảng cách",
    closeFacilityDetailAria: "Đóng chi tiết cơ sở",
    searchResultSuffix: "kết quả",
    latitudeLabel: "Vĩ độ",
    longitudeLabel: "Kinh độ",
    directionsButton: "Chỉ đường",
    directionsNeedGps: "Vui lòng cấp quyền vị trí để mở chỉ đường.",
    sosHereButton: "SOS đến đây",
    locationRequesting: "Đang xác định vị trí GPS...",
    locationReady: "Đã cập nhật vị trí hiện tại.",
    locationDenied: "Cần cấp quyền GPS để sử dụng tính năng này.",
    locationFailed: "Không thể lấy vị trí. Vui lòng thử lại.",
    sosButton: "🚨 SOS Khẩn Cấp",
    sosPrepareError: "Không thể gửi SOS khi chưa có vị trí.",
    sosModalTitle: "Xác nhận gửi yêu cầu SOS",
    sosModalSubtitle: "Vị trí sẽ được gửi tới trung tâm điều phối cấp cứu.",
    sosPhoneLabel: "Số điện thoại nạn nhân",
    sosPhonePlaceholder: "Ví dụ: 0901234567",
    sosPhoneRequired: "Vui lòng nhập số điện thoại.",
    sosPhoneInvalid: "Số điện thoại không hợp lệ.",
    sosCancel: "Hủy",
    sosConfirm: "Xác nhận và gửi SOS",
    sosSending: "Đang gửi yêu cầu SOS...",
    sosSendFailed: "Gửi SOS thất bại. Vui lòng thử lại.",
    sosSuccessTitle: "Yêu cầu SOS đã được gửi!",
    sosSuccessBody: "Đang chờ điều xe...",
    assignedHospitalLabel: "Bệnh viện phụ trách",
    assignedHospitalHotline: "Hotline",
    trackingFallback: "Đang chờ điều xe...",
    trackingAssigned: "Xe cứu thương đã được điều phối.",
    trackingEtaPrefix: "Xe cứu thương cách bạn",
    trackingEtaSuffix: "phút",
    trackingReconnect: "Đang kết nối lại...",
    trackingModeBadge: "Chế độ theo dõi cấp cứu",
    rescueCompleted: "Xe cứu thương đã đến nơi.",
    locationStatusUnknown: "Chưa có vị trí hiện tại.",
    sessionNotFound: "Không tìm thấy phiên làm việc. Vui lòng gửi SOS mới hoặc đăng nhập để tra cứu.",
    returnToMap: "Quay lại bản đồ",
    emptyWithinRadius: "Không tìm thấy cơ sở phù hợp trong phạm vi hiện tại.",
    emptySuggestExpandToTenKm: "Chưa có cơ sở trong phạm vi này. Hãy thử tăng bán kính lên 10 km.",
    emptySuggestExpandBeyondTenKm: "Chưa có cơ sở trong bán kính 10 km. Bạn có thể mở rộng phạm vi để tìm thêm.",
    retry: "Thử lại",
} as const;
