/**
 * Centralized guest-facing UI copy to keep localization updates in one place.
 */

export const guestStrings = {
    facilityPanelTitle: "Cơ sở y tế gần bạn",
    facilityPanelCloseLabel: "Đóng",
    facilityPanelCloseMapAria: "Đóng danh sách — xem bản đồ",
    facilityPanelOpenListLabel: "Xem danh sách",
    facilityPanelCompactHint: "Chạm để mở bộ lọc và danh sách cơ sở",
    searchPlaceholder: "Tìm theo tên cơ sở...",
    radiusLabel: "Bán kính tìm kiếm",
    loadingFacilities: "Đang tải danh sách cơ sở...",
    facilityLoadError: "Không thể tải dữ liệu cơ sở y tế. Vui lòng thử lại.",
    noFacilities: "Không tìm thấy cơ sở phù hợp trong phạm vi hiện tại.",
    locateButton: "Định vị",
    hospitalScreenButton: "Bệnh viện",
    facilityTypeAll: "Tất cả",
    facilityTypeHospital: "Bệnh viện",
    facilityTypeClinic: "Phòng khám",
    facilityTypePharmacy: "Nhà thuốc",
    facilityTypeHospitalVi: "Bệnh viện",
    facilityTypeClinicVi: "Phòng khám",
    facilityTypePharmacyVi: "Nhà thuốc",
    detailTitle: "Chi tiết cơ sở",
    detailLabelType: "Loại",
    detailLabelAddress: "Địa chỉ",
    detailLabelHotline: "Hotline",
    detailLabelOpeningHours: "Giờ mở cửa",
    detailLabelDistance: "Khoảng cách",
    detailLabelEtaApprox: "Ước tính tới nơi",
    detailPhoneFallback: "Chưa có số hotline",
    detailOpeningHoursFallback: "Chưa cập nhật giờ mở cửa",
    detailDistanceFallback: "Chưa xác định khoảng cách",
    closeFacilityDetailAria: "Đóng chi tiết cơ sở",
    searchResultSuffix: "kết quả",
    latitudeLabel: "Vĩ độ",
    longitudeLabel: "Kinh độ",
    directionsButton: "Chỉ đường",
    directionsNeedGps: "Vui lòng cấp quyền vị trí để mở chỉ đường.",
    directionsNoGpsHint: "Mở Google Maps tại cơ sở. Bật GPS để chỉ đường từ vị trí hiện tại.",
    sosHereButton: "SOS đến đây",
    locationRequesting: "Đang xác định vị trí GPS...",
    locationReady: "Đã cập nhật vị trí hiện tại.",
    locationDenied: "Cần cấp quyền GPS để sử dụng tính năng này.",
    locationDeniedPromptHint: "Bấm «Thử lại» và chọn Cho phép khi trình duyệt hỏi quyền vị trí.",
    locationDeniedSettingsHint:
        "Nếu không thấy hộp thoại: bấm biểu tượng khóa hoặc tên trang trên thanh địa chỉ → Vị trí → Cho phép, rồi bấm «Thử lại».",
    locationFailed: "Không thể lấy vị trí. Vui lòng thử lại.",
    locationOutsideSupportedArea:
        "Vị trí của bạn nằm ngoài khu vực hỗ trợ. Hiện hệ thống chỉ phục vụ tại TP. Hồ Chí Minh.",
    locationOutsideSupportedAreaTitle: "Ngoài khu vực hỗ trợ",
    locationOutsideSupportedAreaBody:
        "Ứng dụng và dữ liệu cơ sở y tế hiện chỉ áp dụng cho TP. Hồ Chí Minh. Vui lòng di chuyển vào khu vực này để sử dụng định vị và SOS khẩn cấp.",
    locationOutsideSupportedAreaRetry: "Thử định vị lại",
    sosButton: "SOS khẩn cấp",
    sosPrepareError: "Không thể gửi SOS khi chưa có vị trí.",
    sosModalTitle: "Xác nhận gửi yêu cầu SOS",
    sosModalSubtitle: "Vị trí sẽ được gửi tới trung tâm điều phối cấp cứu.",
    sosPhoneLabel: "Số điện thoại nạn nhân",
    sosPhonePlaceholder: "Ví dụ: 0901234567",
    sosPhoneRequired: "Vui lòng nhập số điện thoại.",
    sosPhoneInvalid: "Số điện thoại không hợp lệ.",
    sosCancel: "Hủy",
    sosConfirm: "Xác nhận và gửi SOS",
    sosSending: "Đang gửi yêu cầu SOS...",
    sosSendFailed: "Gửi SOS thất bại. Vui lòng thử lại.",
    sosSuccessTitle: "Yêu cầu SOS đã được gửi!",
    sosSuccessBody: "Đang chờ điều xe...",
    assignedHospitalLabel: "Bệnh viện phụ trách",
    assignedHospitalHotline: "Hotline",
    trackingFallback: "Đang chờ điều xe...",
    awaitingDispatchSuffix: "đang tiếp nhận yêu cầu của bạn. Vui lòng chờ điều phối xe.",
    awaitingDispatchFallback: "Bệnh viện đang tiếp nhận yêu cầu của bạn. Vui lòng chờ điều phối xe.",
    awaitingDispatchBadge: "Đang chờ điều phối",
    trackingAssigned: "Xe cứu thương đã được điều phối.",
    trackingEtaPrefix: "Xe cứu thương cách bạn",
    trackingEtaSuffix: "phút",
    trackingReconnect: "Đang kết nối lại...",
    trackingOffline: "Mất kết nối mạng — đang chờ kết nối lại...",
    trackingModeBadge: "Chế độ theo dõi cấp cứu",
    rescueCompleted: "Xe cứu thương đã đến nơi.",
    locationStatusUnknown: "Chưa có vị trí hiện tại.",
    sessionNotFound: "Không tìm thấy phiên làm việc. Vui lòng gửi SOS mới hoặc đăng nhập để tra cứu.",
    returnToMap: "Quay lại bản đồ",
    emptyWithinRadius: "Không tìm thấy cơ sở phù hợp trong phạm vi hiện tại.",
    emptySuggestExpandToTenKm: "Chưa có cơ sở trong phạm vi này. Hãy thử tăng bán kính lên 10 km.",
    emptySuggestExpandBeyondTenKm: "Chưa có cơ sở trong bán kính 10 km. Bạn có thể mở rộng phạm vi để tìm thêm.",
    emptySuggestOpenAdvanced: "Không có cơ sở trong phạm vi 5 km. Mở Tùy chọn nâng cao để tìm xa hơn.",
    advancedOptionsToggleShow: "Tùy chọn nâng cao",
    advancedOptionsToggleHide: "Thu gọn tùy chọn",
    radiusFixedSummary: "Phạm vi: 5 km — ưu tiên cơ sở gần nhất",
    radiusAdvancedNeedsGps:
        "Bật «Định vị» để dùng bán kính tùy chỉnh — danh sách và marker sẽ lọc theo khoảng cách thực từ GPS của bạn.",
    /** Tooltip nút / thanh trượt (TC07) */
    radiusSliderNeedGpsTooltip: "Cần bật định vị (GPS) để lọc theo bán kính từ vị trí của bạn.",
    showingNearestSummary: "Gần nhất",
    facilitiesWord: "cơ sở",
    callNowButton: "Gọi ngay",
    facilityOpenNowBadge: "Đang mở",
    facilityClosedBadge: "Đóng cửa",
    facilityOpenUnknownBadge: "Chưa rõ giờ",
    facilityCardRankAria: "Thứ hạng gần nhất",
    hotlineTapHint: "Bấm để gọi ↓",
    sosAcquiringLocation: "Đang lấy vị trí cho SOS…",
    sosAcquiringLocationSub: "Giữ nguyên màn hình, không tắt ứng dụng.",
    guestAnonymousBadge: "Ẩn danh",
    guestAnonymousHint: "Đăng nhập để gửi kèm hồ sơ y tế (tuỳ chọn).",
    guestMedicalProfileHint: "Hồ sơ y tế sẽ gửi kèm SOS khi có yêu cầu.",
    locationStatusCompactReady: "Đã định vị",
    locationStatusCompactUnknown: "Chưa định vị",
    etaApproxSuffix: "phút (ước tính)",
    retry: "Thử lại",
} as const;
